### ISSUE TITLE
Unicode bug - release fix

### ISSUE THREAD

**Issue by Ethanweiner20** [c-okelly/anki-remote-decks#10]
I would love to see support for all unicode characters (at the moment, using any characters not within ASCII give an error). This plugin is easily the most useful Anki add-on I have ever found, thank you so much for creating and updating this.

**Comment by c-okelly** [comment]
@Ethanweiner20 this issue has been fixed but I have not released it yet. Was waiting to bundle it with something else but that fix is taking to long so will push this one as is on the next few days

**Comment by c-okelly** [comment]
Released in v1.2.1 and should now be available. Let me know if there are any issues
