### ISSUE TITLE
Problem adding a new remote deck (Google docs)

### ISSUE THREAD

**Issue by hjordisasta** [c-okelly/anki-remote-decks#100]
Hi,

I cannot add a new rermote deck, it is a google docs one, with bulletins. Never had this problem before. Please help, I love this addon so much!
This was the error message:

The error was 400 Client Error: Bad Request for url: https://lh6.googleusercontent.com/n7aBeLdB6WiGeEGrpxkJpO7VNbGpYjPNMZPmIqaDSqfi2Qq2QkAFlTOcrtZSgFuRzlUghxAf7AhWw3h_Jm6Fjj21l1Xn2mNSuSimL81RoZ8bE-4R3ap1gxtrR0m3iQQTC.
If you would like me to fix it please report it here: https://github.com/c-okelly/anki-remote-decks/issues
Please be sure to provide as much information as possible. Specifically the file the caused the error.

**Comment by c-okelly** [comment]
Going to close this for #98 and track it there. Seems likely it is the same issue for all of them
