### ISSUE TITLE
Error 400, Remote Decks

### ISSUE THREAD

**Issue by leoprob98** [c-okelly/anki-remote-decks#101]
Hi!

It seems that I am experiencing the same issue as many fellow Anki users. When I try to add my remote deck in my app, the error 400 pops up. I have read that if you eliminate the images on the document it works fine, nonetheless, I really need to keep the images on my remote decks. Is there any way this bug can be fixed?

Thanks!

**Comment by c-okelly** [comment]
Going to close this for #98 and track it there. Seems likely it is the same issue for all of them
