### ISSUE TITLE
Google Docs not working

### ISSUE THREAD

**Issue by ChocoTonic** [c-okelly/anki-remote-decks#11]
Could you upload a editable Google document that I could make a copy of and test the features of the addon? It appears to not be working for me when I try to generate my own cards

![image](https://user-images.githubusercontent.com/41702116/65365401-f2374d80-dbcd-11e9-88c6-cbcafb6db095.png)

![image](https://user-images.githubusercontent.com/41702116/65365409-f95e5b80-dbcd-11e9-9ba7-1ed134d398e5.png)

actually, could you just upload this version of a Google document?
seemed like an oversight to not include a Google document people could make a copy of and try for themselves rather than an already published Google document

https://github.com/c-okelly/anki-remote-decks/issues

![image](https://user-images.githubusercontent.com/41702116/65365801-73dcaa80-dbd1-11e9-8ee3-397d7c774b44.png)

**Comment by c-okelly** [comment]
Hey I has just updated the docs to include a link to the google doc as you suggested! 

I probably should have done it to start with but did not think of it

Closed by a020ee94daa472180da580afcc515bb427084536

**Comment by c-okelly** [comment]
Hey I has just updated the docs to include a link to the google doc as you suggested! 

I probably should have done it to start with but did not think of it

Closed by a020ee94daa472180da580afcc515bb427084536
