### ISSUE TITLE
Option to change syntax of card addition

### ISSUE THREAD

**Issue by ChocoTonic** [c-okelly/anki-remote-decks#12]
This is a wonderful addon concept, but the forced bullet list formatting of the backside is not desirable. 

Would it be possible to change what the addon would recognize as the front vs the back instead of using the tabs and bullet hierarchy? 
say with {Front} {/Front} and {Back} {/Back} as examples

**Comment by c-okelly** [comment]
Hey,

I'm currently away so have not been able to reply very quickly! It is currently possible to change the formatting for the back of the card.
It can be done using the following syntax:

```org
* Question
# list=false
  * Answer

```

There was another few comments about changing up the formatting but I do think that the current way of doing it quite user friendly for the general user. I might try something like that in the future though!

**Comment by c-okelly** [comment]
Fixed in f0ac620
