### ISSUE TITLE
Ascii error?

### ISSUE THREAD

**Issue by fneurohr22** [c-okelly/anki-remote-decks#13]
“Hey there! It seems an error has occurred while running.

The error was 'ascii' codec can't encode character '\xa0' in position 27: ordinal not in range(128).

If you would like me to fix it please report it here: https://github.com/c-okelly/anki-remote-decks/issues

Please be sure to provide as much information as possible. Specifically the file the caused the error.“

**Comment by c-okelly** [comment]
Hey I think this is related to #10. There is a is currently a unicode issue and I need to release the next fix on Anki.

It is related to using characters such as "ó".

Unfortunately I'm away at the moment and not able to test the next fix until I get back. I will update when I have pushed it

**Comment by fneurohr22** [comment]
Perfect, thank you. How long until you are back? We are using this deck to study for an anatomy Exam in 1 month.

**Comment by c-okelly** [comment]
This should be fixed now in release v1.2.1 in 147e87b5b0d5ebad5d6c398331ccf1049a62bfed
