### ISSUE TITLE
images not showing up, even after trying to “edit“ them

### ISSUE THREAD

**Issue by fneurohr22** [c-okelly/anki-remote-decks#14]
Remote deck pictures arent showing up. 
![Screen Shot 2019-09-27 at 4 25 48 PM](https://user-images.githubusercontent.com/54685509/65805660-ac393700-e143-11e9-9eba-bddc2c15467e.png)

![Screen Shot 2019-09-27 at 4 27 32 PM](https://user-images.githubusercontent.com/54685509/65805680-be1ada00-e143-11e9-82d1-485b1529c36d.png)

![Screen Shot 2019-09-27 at 4 28 37 PM](https://user-images.githubusercontent.com/54685509/65805714-e30f4d00-e143-11e9-8096-9fe74f3a340e.png)

**Comment by c-okelly** [comment]
Hey,

I spotted this issue a few days ago. I'm working on a fix that should be out shortly.

Unfortunately the IMG actually points to a URL rather then the local copy

**Comment by c-okelly** [comment]
Closed by #16
