### ISSUE TITLE
words showed together with no space between

### ISSUE THREAD

**Issue by fneurohr22** [c-okelly/anki-remote-decks#15]
There should be a space where the red line is. Ive seen it happen on many cards, not just one
![Screen Shot 2019-09-29 at 1 49 25 PM](https://user-images.githubusercontent.com/54685509/65838447-563dce00-e2c0-11e9-8fa9-54b6866ceb4e.png)

**Comment by c-okelly** [comment]
That should be an easy enough fix. Will get on it in the next few hours!

**Comment by c-okelly** [comment]
I'm away till the 20th of October but I will release this fix once I am back!
