### ISSUE TITLE
Square Bracket Bug

### ISSUE THREAD

**Issue by theAlke** [c-okelly/anki-remote-decks#21]
Hi,

Thanks for you great work on this add-on. I I found a bug that occurs when using square brackets. It produces the following error: "The error was expected str, bytes or os.PathLike object, not NoneType"

I reproduced the bug with the following document: https://docs.google.com/document/d/e/2PACX-1vRIR6WhZAnIkjwUsdXOyiGryD9IkrnOrSKeuTZaON00vN19vjW9FrGlhXUW3mRzmYTo5_PrulYNREbV/pub

Thanks for the great work!

----------------------------------------------------------------------------------------

Remote Decks: Version V1.2.1
Anki Version: 2.1.12
Operating Version: MacOS 10.14.6

**Comment by c-okelly** [comment]
Hey,

Really appreciate create a minimum usecase like that. I will try and get the fix out for this and another bug out today

**Comment by c-okelly** [comment]
Issue was in parseData.py in buildNamedDeck

Should not have inserted a ```None``` value on line 19

**Comment by c-okelly** [comment]
I'm away till the 20th of October but I will release this fix once I am back!
