### ISSUE TITLE
Note model is missing - error on import

### ISSUE THREAD

**Issue by kolmberger** [c-okelly/anki-remote-decks#22]
Hi there,
I would love to use your add-on. Tried it first time today, but throws me an error on the sample doc.
![image](https://user-images.githubusercontent.com/35469696/66341252-2ab58600-e947-11e9-970b-2b6f4a61a124.png)

The published doc is: https://docs.google.com/document/d/e/2PACX-1vR-rEbb7oyFN_anEcMk7--QWSuBz7Hdgu5FEHS7JTKBwCBiopQj19N0rs4Gwbz7xIpuVevl0Rcqda3N/pub

What am I doing wrong?
Cheers and thanks!

**Comment by c-okelly** [comment]
Hey @kolmberger,

Are you by any chance using a non English version of Anki? There error seems to be that you do not have the Basic not model available in your note templates. Did you delete it by any chance? It should be available by default

**Comment by kolmberger** [comment]
Hi @c-okelly ,
thanks for your quick answer :) I downloaded and installed Anki from here: https://apps.ankiweb.net/ 64bit version and didn't do any modifications / deletions at all, since I only wanted to use it for my studies.
Any recommendations to use an alternative version?
Cheers!

**Comment by c-okelly** [comment]
You should be able to fix it by doing the following:

Got to => Tools -> Manage Note Types

Then click Add card

You should see something like this:

![Screen Shot 2019-10-08 at 14 07 23](https://user-images.githubusercontent.com/8889083/66371302-65fe9600-e9d5-11e9-8c6e-132759730106.png)

The required card type should be there as highlighted in Green. The card you need to add is annotated in Red

Then you need to the basic note type.

**Comment by kolmberger** [comment]
Solved, thank you! I did a re-installation meanwhile, which did it. But now I am aware, to have an eye on the note type. A beginners problem... 
Thanks a lot, I really appreciate this add-on. Pretty piece of work.
Cheers.

**Comment by c-okelly** [comment]
Great to hear. I think long term I might just get the add-on to creates it's own note types so that issues like this don't happen in future but until then I hope this helps!

**Comment by c-okelly** [comment]
Also if you enjoy it feel free to give me a star!! haha

![3coblb](https://user-images.githubusercontent.com/8889083/66375956-2e95e680-e9e1-11e9-88f2-5a4ded688015.jpg)
