### ISSUE TITLE
control the note type during import

### ISSUE THREAD

**Issue by kolmberger** [c-okelly/anki-remote-decks#23]
Hi Conor,
is there a chance, to control to which note type the remote decks are imported to?
In my case, I want to import it to type "basic (and reversed card)"
Thanks! :)

**Comment by c-okelly** [comment]
Hey!

Yes there is actually and it already works. Apologies I will update the documentation to include how to do it!

**Comment by kolmberger** [comment]
Hey @c-okelly, i just wanted to check, if you already managed to update the documentation for controlling the target note type? I recently checked, found some common updates in the docu, but not yet anything about the note type. 
Thanks a lot.
Cheers!

**Comment by c-okelly** [comment]
Hey @kolmberger,

I'm currently away at the moment so had not got around to doing it! I will be back tomorrow.

In the mean time I will just but the docs below. You need to make sure note type is exactly the same as in the Anki application.

This would set the note to a basic and reversed type:
```org
* Question line
# type = Basic (and reversed card)
    * Answer line
```

This would set the note to a Cloze
```org
* When was Dublin founded {{c1::1204}}
# type=Cloze
    * Extra Info
```

**Comment by kolmberger** [comment]
Much appreciated! Thanks

**Comment by c-okelly** [comment]
Also if you are interested there is some more experimental docs on this page:

[org_to_anki docs](https://github.com/c-okelly/org_to_anki/blob/master/documentation/orgReadme.md)

It "should" all work. Though I def do not support the multi level decks correctly yet!

**Comment by c-okelly** [comment]
Updated in 8a2500f
