### ISSUE TITLE
size of images in imported remote deck

### ISSUE THREAD

**Issue by kolmberger** [c-okelly/anki-remote-decks#24]
Hi @c-okelly,
my use case: I create and publish a google docs file on my computer. Simultaneously, I open the google doc on my mobile. At the targeted position, I insert an image from the camera, because in my case I have to take a photo of the study material. Even if I directly crop the picture on the phone before importing it to the google doc, it is mostly way too large in the cards.
I have these addons installed in additon to remote decks:

- Image Occlusion Enhanced for Anki 2.1 alpha
- ImageResizer
- Maximum image height in card editor

But none of them react on an imported deck, and that brings the too large pictures to the cards. 

IMO on the PC it's not fun to study cards with such big pictures, to me, the pics are kind of a little helper, but no high detail info.

With the addons mentioned, of course I could edit the pics in the cards somehow, but after a new remote sync of the decks, the initial size is restored.

Could that be controlled by any chance?

Thanks! :)

**Comment by kolmberger** [comment]
Additional info for my use case: I also use to study on the mobile phone. As far as I have seen, the size of the pictures don't matter, they are adjusted to the size of the screen.

On the PC, big pictures exceed the borders of the screen/window and are not displayed as a whole.

**Comment by kolmberger** [comment]
![2019-10-11 08_17_24-Clipboard](https://user-images.githubusercontent.com/35469696/66628838-5020e900-ec00-11e9-9764-fe071464b81e.jpg)

**Comment by c-okelly** [comment]
Hey,

I will have a look into this and try to come up with a strategy for dealing with it.

It def should not go past the borders at the very least. I think I will have to add some logic to allow the user to control the size of the image from the Google Docs.

I will work on this at the top of the list but I'm a bit restricted at the moment with how much I can get done.

**Comment by c-okelly** [comment]
Also an update on this.

My proposed solution would be as follows:

The picture size that is set in the document would be respected so that is should be the same in the actual card. 

If you make it bigger in the doc it will make it will make it bigger in the card. This would be the first pass solution anyway

Do you think that makes sense from a users perspective?

**Comment by kolmberger** [comment]
> The picture size that is set in the document would be respected so that is should be the same in the actual card.

> If you make it bigger in the doc it will make it will make it bigger in the card. This would be the first pass solution anyway
Actually, I am not so sure about this. 
This is how i did it:
- open the gdoc on my mobile
- put the cursor, where the pic will go to
- take a picture with the mobile camera
- insert the picture into gdoc
- since such pics are quite large, select the image in gdoc
- pull an outer corner and reduce the size of the picture
![image](https://user-images.githubusercontent.com/35469696/67771024-c83c3b00-fa57-11e9-9e19-4ffaa9c6a04a.png)

Doing it this way reduces the size in gdoc, but it will be imported as large into anki, as screenshotted in the first comment

**Comment by c-okelly** [comment]
Ye currently the picture size is set by the actual size of the base image that is added and it does not respect an adjustment done by the users.

This solution would allow you to change the size by editing the image in the doc

**Comment by kolmberger** [comment]
There is an add-on for gdoc, "set image size". I will fiddle around with it a bit. Maybe I can mass-adjust with it.
![image](https://user-images.githubusercontent.com/35469696/67772084-c5424a00-fa59-11e9-82a6-75a64cd1255f.png)

**Comment by c-okelly** [comment]
Should be fixed by #32

**Comment by c-okelly** [comment]
Closed
