### ISSUE TITLE
Issue adding remote deck - HTTPSConnectionPool ... Read time out

### ISSUE THREAD

**Issue by Albarbis** [c-okelly/anki-remote-decks#26]
Hi!

I am having a problem adding a remote deck from a google doc.  Normally there is no issue, but this time I am getting this error:
The error was HTTPSConnectionPool(host='lh3.googleusercontent.com', port=443): Read timed out..

Any advice?

Thanks!

**Comment by c-okelly** [comment]
Hey,

This is a known issue due to your internet connection timing out to Google. It is most likely due to a slow internet connection.

I currently have no retry stratey. This might also be triggered by too many requests to a single page

**Comment by Albarbis** [comment]
Ok.  Thanks so much for the help.  Anki is a real life saver. :D
