### ISSUE TITLE
Color stopped showing on some cards

### ISSUE THREAD

**Issue by fneurohr22** [c-okelly/anki-remote-decks#27]
on the google docs:
![Screen Shot 2019-10-27 at 4 43 28 PM](https://user-images.githubusercontent.com/54685509/67643100-0b23d480-f8d9-11e9-9a9c-0981b6ed1b4b.png)

on anki:
![Screen Shot 2019-10-27 at 4 42 20 PM](https://user-images.githubusercontent.com/54685509/67643103-137c0f80-f8d9-11e9-8fc1-c27f31fc05d8.png)

**Comment by c-okelly** [comment]
Hey,

Can you please update to the latest version and double check that this is still happening? I'm struggling to replicate the issue

**Comment by c-okelly** [comment]
Could not replicate issues
