### ISSUE TITLE
Spaced are being removed inbetween words with no Bold and words with Bold.

### ISSUE THREAD

**Issue by fneurohr22** [c-okelly/anki-remote-decks#28]
On google docks Bold working normally:
![Screen Shot 2019-10-27 at 4 46 51 PM](https://user-images.githubusercontent.com/54685509/67643137-8e452a80-f8d9-11e9-91ca-7f7b95d5cf7b.png)

On anki spaces between words with bold not working propertly:
![Screen Shot 2019-10-27 at 4 46 40 PM](https://user-images.githubusercontent.com/54685509/67643138-90a78480-f8d9-11e9-99ce-38a0d6032c71.png)

**Comment by c-okelly** [comment]
Strange. I thought I had fixed this. I assume you are on the latest version of the Add-on?

I will double check anyway

**Comment by c-okelly** [comment]
I'm also struggling to replicate this issues. By any chance did you move the card out of the deck is was originally uploaded to?

**Comment by c-okelly** [comment]
Could not replicate issues
