### ISSUE TITLE
Support formatting

### ISSUE THREAD

**Issue by c-okelly** [c-okelly/anki-remote-decks#3]
Supporting the following formatting:

- [ ] Bold
- [ ] Italics
- [ ] Underlined
- [ ] Colored

User should be able to set this in Google docs and should be reflected in the Anki cards itself

**Comment by fneurohr22** [comment]
Yay I’m so excited for this update!

**Comment by c-okelly** [comment]
Completed by #6. Should be updated in the next few houres
