### ISSUE TITLE
Type or tags by section instead of by each card

### ISSUE THREAD

**Issue by thn2-mdphd** [c-okelly/anki-remote-decks#33]
Great addon. Is there a way to quickly set a section of cards as a specific tag or as a type=Cloze without having to specify it to each card?

**Comment by c-okelly** [comment]
Unfortunately not at this time. You could set the type for card at the top of the file but this would then set it for all of the cards in the document

**Comment by thn2-mdphd** [comment]
That's exactly what I would like. I've tried to set a global variable on the google docs like here at the top with # type = Cloze with this example document https://docs.google.com/document/u/1/d/18GGj3I_7rdQxOiW5X9MZd1ooCIyMnLsuR_2z3B_ib2I/pub and it doesn't seem to recognize the cards as Cloze format but rather as the default basic format? 

Furthermore, would you be able to demonstrate how #fileType = topics works using the Google Docs? I'd like to be able to split my Google Doc into multiple decks. Thank you very much for your time.

**Comment by c-okelly** [comment]
Sorry I must have missed your reply.

Ye Cloze cards are bit difficult to delimit between cards as they don't actually require the second line.

e.g is this two cards or one?

* Test1 {{c1::test3}}
* Test2 {{c1::test3}}

Unfortunately the addon does not support mulit-deck hierarchies as this time as it makes it a lot more complicated to update and manage cards. The biggest issues is moving from one deck to another. Though I do have it in the general backlog to look at

**Comment by c-okelly** [comment]
Multi deck support is tracked by #17 though to be fair it has been open for a while now
