### ISSUE TITLE
image height and width of images added as comment

### ISSUE THREAD

**Issue by kolmberger** [c-okelly/anki-remote-decks#35]
Hey, the image size is in gdocs is now recognized in Anki (which is great!), though I might found a new thing.

If you got a constellation like this in gdocs:
![image](https://user-images.githubusercontent.com/35469696/69912332-19a96280-1428-11ea-8878-63702c47324e.png)

you get this in Anki preview:
![image](https://user-images.githubusercontent.com/35469696/69912342-4b222e00-1428-11ea-918a-9f80383b95ab.png)
Anki study mode:
![image](https://user-images.githubusercontent.com/35469696/69912359-9d634f00-1428-11ea-976d-7765e8c6bcaf.png)

With my environment, it adds the width and height of a picture as a comment at the end of the next line, if it exists. 

If the picture is the last thing in the answer, nothing is added (as expected).
![image](https://user-images.githubusercontent.com/35469696/69912336-2cbc3280-1428-11ea-9880-dabd438c4ca4.png)

![image](https://user-images.githubusercontent.com/35469696/69912347-642adf00-1428-11ea-9910-a297daca3392.png)

![image](https://user-images.githubusercontent.com/35469696/69912362-afdd8880-1428-11ea-8fdd-5862352d8f2e.png)

The note type doesn't matter, I tried it also with basic card.

A known issue or maybe only on my side?
Cheers!

**Comment by c-okelly** [comment]
Hey,

That is a bug for sure. There is an intermediate state of the document where it uses the comment to transfer the information about size. I would not have expected this to happen but I will look into it and put out a solution.

Thanks for the error report

**Comment by c-okelly** [comment]
Bug fix in pr #45 

Once build will merge and release and then close this issues

**Comment by c-okelly** [comment]
Fixed and released in v1.5.0
