### ISSUE TITLE
Can't seem to generate cloze cards.

### ISSUE THREAD

**Issue by denzilholles** [c-okelly/anki-remote-decks#36]
I try to make cloze cards with the syntax listed in the documentation, but it doesn't work. Instead, I get basic cards with the following text:
`Question is {{c1::question?}} # type = Cloze`

**Comment by denzilholles** [comment]
Oh I figured it out. # has to be on a new line for it to work.
![image](https://user-images.githubusercontent.com/42273835/70486434-d1411300-1abf-11ea-8254-4b7fffd9bcd2.png)
Ie
`Question is {{c1::x}}
#type=Cloze`
works well

**Comment by c-okelly** [comment]
Hey,

Ye Cloze are bit of an edge case as you can have single line cloze cards. Compared to most others are would required multiple lines
