### ISSUE TITLE
The error was 'ascii' codec can't encode character '\u2019' in position 97: ordinal not in range(128).

### ISSUE THREAD

**Issue by denzilholles** [c-okelly/anki-remote-decks#37]
Hi everyone, 

When I tried to make a new remote deck, I got the following error: 

> Hey there! It seems an error has occurred while running.
> The error was 'ascii' codec can't encode character '\u2019' in position 97: ordinal not in range(128).
> If you would like me to fix it please report it here: https://github.com/c-okelly/anki-remote-decks/issues
> Please be sure to provide as much information as possible. Specifically the file the caused the error.

Here is the google doc I am trying to make cards out of: https://docs.google.com/document/d/e/2PACX-1vQM1m4IJsrYRkLDMqylxxhPWLCy6eTVNMCN6WB-6n-3nfg9Qd-sYqNtxBHf3hKYKgmh1qfW6EiM8HSe/pub

**Comment by denzilholles** [comment]
![image](https://user-images.githubusercontent.com/42273835/72474764-851c7900-37b7-11ea-94ee-f0fea21743da.png)

**Comment by denzilholles** [comment]
\u2019 refers to the `'` character. I tried removing all instances of the `'` character but the addon gives me the same error.

**Comment by denzilholles** [comment]
Okay, I figured out a end-user work around. 

1. Find the u/char flag that's causing the error and delete it from your Google Doc. 
2. Copy & paste your text into a new Google Doc and re-publish it to the web.
3. Upload the Google Doc into Remote Decks. 

My guess it that Google Docs doesn't update the Google Doc fast enough to reflect the removed characters.

My request is for this addon to support more characters. Specifically `' → ↑ ↓`. 

Thanks again for this amazing add-on. It has truly improved my workflow.

**Comment by heaneySam** [comment]
I have the same issue, it only seems to be a problem on Mac for me. We can also add u/2013 (the dash symbol). I do not have this problem on any Windows machines. The workaround above works, but I'd quite like to be able to use apostrophes and dashes!

By the way I absolutely love this addon, it is really helping me out!

**Comment by c-okelly** [comment]
Strange you are getting different results on different machines. There should be supported for not utf-8 characters.

I'll have a look at it and get back to you!

**Comment by c-okelly** [comment]
It also takes about 5 minutes for the published version to actually update for Google Docs. Not really sure why they do it like this but they do!

**Comment by c-okelly** [comment]
Ye this is a strange issue. I think it is only happening on osx which is a pain. I can't replicate the issue on Linux. I'll see if I can get my hands on a mac vm

**Comment by heaneySam** [comment]
That would be amazing. Thankyou for all your work on this.

**Comment by denzilholles** [comment]
Yes, I am also a Mac OSX user (Mojave 10.14.8). Using Chrome Version 79.0.3945.130 (Official Build) (64-bit).

**Comment by denzilholles** [comment]
> Ye this is a strange issue. I think it is only happening on osx which is a pain. I can't replicate the issue on Linux. I'll see if I can get my hands on a mac vm

Thank you for your help on this. This is a amazing add-on and has revolutionized my workflow.

**Comment by heaneySam** [comment]
For what it's worth I'm on macOS 10.15 Beta (19A582a) **Catalina**

**Comment by c-okelly** [comment]
Hummm I got a Catalina iso image so trying to build a vm at the moment. Slow going though

**Comment by c-okelly** [comment]
It is becoming very difficult to get my hands on a working Catalina VM. It appears that 10.15.2 is not bootable in virtual box at this time. 

I don't have access to a 10.15.1 image but I'm trying to find one online.

The fall back to this will be to try and create a test plugin that I can share with you to test manually if any of you would be able to do that?

**Comment by heaneySam** [comment]
Yeah I’m happy to help of course. Send it here?

**Comment by c-okelly** [comment]
I got a VM running eventually. I have a fix pretty much finished. Just testing now and will release

**Comment by c-okelly** [comment]
This should be fixed. I released and tested against your deck on OSX Catalina. 

Please let me know if this is not the case

**Comment by denzilholles** [comment]
Beautiful! I just tested it on my computer and the characters `↑ ↓ → '` are now supported.

Using macOS Mojave 10.14.6.

**Comment by c-okelly** [comment]
Great! They should have worked previously. It was just some poor unicode handling when it game to logging
