### ISSUE TITLE
Note models should be added if not present - problem with adding new Deck 

### ISSUE THREAD

**Issue by ahmedbenarab** [c-okelly/anki-remote-decks#38]
I am using anki-remote-decks on : 

- windows 10 
- Anki 2.1.19 last version 

it is the first time that i install this add-on on Anki ,
the add install normally but when i add a new deck from google docs link it show me this window 
![image](https://user-images.githubusercontent.com/21174375/72559947-487b7b00-38a6-11ea-9fe6-ceb6a1b4dd14.png)
 then an empty decks is created that contain no cards , i tried to reinstall the add-on and restart anki but no thing change 
i think this have a relation with the last update of Anki (may be ) , or perhaps the problem is in the updates of google docs 
have a nice day

**Comment by c-okelly** [comment]
Can you send me a link to the deck and I will have a look!

**Comment by c-okelly** [comment]
My guess is that one of your notes is malformed and it's trying to create a note that has a part missing. Issue could be how I'm parsing though equally

**Comment by ahmedbenarab** [comment]
> 
> 
> Can you send me a link to the deck and I will have a look!

I created a sample decks to try and figure out how the add-on works
link : https://docs.google.com/document/d/e/2PACX-1vS3yD7xibKhSRUspVbV8Xg-Skzu8mztscZ16nYNhTgq_k64Dfw66mpmq3uTC9G011nHBZCVy8gZk6rK/pub
i followed all the instructions that i have found on github , but i still doesn't work so i tried to use your example 
link : https://docs.google.com/document/d/e/2PACX-1vTXfHfgGXDygnzs0IQK0Yy1o40ptbagqsRVH-NJtaD2vCRlzx2iV6o6T8AZYbTVsmUNFZx12NQAhmuH/pub
but no things change it still show me the same error window after creating empty decks

**Comment by c-okelly** [comment]
Are you using anki in another language by any chance?

**Comment by c-okelly** [comment]
Could you send me a list of the available note models you have? Just a screenshot

**Comment by ahmedbenarab** [comment]
![Screenshot_20200118-024550](https://user-images.githubusercontent.com/21174375/72656605-bd30e100-399c-11ea-8dee-e9ebd6b6a968.png)

Yes i use Arabic note models
This are the screen shots from ankidroid but they are the same with anki desktop

**Comment by c-okelly** [comment]
Ye that makes a lot more sense then. The error code if still strange though!

The add-on expects you to have English named note models. I'll add a fix but as a work around you could just add the English note models?

**Comment by ahmedbenarab** [comment]
You mean that I should use the "basic" note model ?

**Comment by c-okelly** [comment]
Exactly. You might need the `Cloze` and `Basic (and reversed card)`  ones as well.

I will make a fix for this so that the add-on detects if they are missing in future and uploads them. So I will leave this issue open but hopefully that solves it for you!

**Comment by ahmedbenarab** [comment]
@c-okelly  thank you man , i have fixed the problem , i think that i have a problem with my account , because even when i removed  all my arabic notes models it still show me the same error window , but the solution was just switching profile to new one , now the add-on work perfectly ,
the first one i created my account in 2016 i opened it in arabic so all my settings variables are in arabic i think , so may be this is the problem but now it work for me perfectly 
thank you for this great and useful  add-on bro have a nice day

**Comment by StohanzlMart** [comment]
> Exactly. You ~~might~~ need the `Cloze` and `Basic ` ones ~~as well~~.

**Comment by babstar99** [comment]
I'm also having exactly the same issue and message as the original report.  Here is a link to my test deck:
https://docs.google.com/document/d/e/2PACX-1vSjNnJ23lOyInwkECDO_mKSxO3G8lIsB788V0PGoY22kr1p9NsUYjwj9UlWObAg9fvofV4Pv5LownqP/pub

**Comment by c-okelly** [comment]
As suggested above it's seems most likely you are missing the default models in English. You will need to manually add then in order to get the plugin to work.

In future the plugin will do this by default

**Comment by babstar99** [comment]
Thank you!  Thank worked, I am new to Anki and finding it has a surprisingly deep and complex series of layers.

**Comment by c-okelly** [comment]
There is a pr in org_to_anki for this. Once that is merged I will release

**Comment by c-okelly** [comment]
Fixed and released in v1.5.0
