### ISSUE TITLE
Bug: Open docx with proper format in Gdocs but wrong format?

### ISSUE THREAD

**Issue by StohanzlMart** [c-okelly/anki-remote-decks#39]
Prepared my doc with the correct indents in mircosoft word and opened the doc with Gdocs.

Doesn't work :(

[0_test.docx](https://github.com/c-okelly/anki-remote-decks/files/4082010/0_test.docx)

Greetings, Martin

**Comment by StohanzlMart** [comment]
[0_test.docx](https://github.com/c-okelly/anki-remote-decks/files/4082053/0_test.docx)

That's the right file,

thanks for working on your awesome Anki-Plugin!

**Comment by c-okelly** [comment]
Hey,

Just having a look at your file there but unfortunately this type of workflow is not supported at all.

While the Google docs bullet points and the Microsoft Word bullet points look very similar they are implemented completely differently. Last time I checked it is actually very difficult to parse this information out of a docx file using current Python libraries.

Even if you copy and past from one to another it might look correct but I would be very surprised if it worked.

**Comment by StohanzlMart** [comment]
Thank you for your response and your great addon!

Got it to work when opening the (unformatted but indented) docx with pictures with gdocs.
Has some bugs though... (Http Error 400 gdocs.com/drawings/foobar/drawing?paren.)

Are there Symbols like "[" and "]" that are not allowed?

**What workflow do you propose from teachers pdf to anki?**

**Comment by StohanzlMart** [comment]
What workflow do you propose from teachers pdf to anki?

Have a nice weekend! Cheers!

**Comment by c-okelly** [comment]
I would suggest that you just write it straight into the Google docs to start with.

It definitely helps the learning experience if you do that rather then copying and pasting.

I have another add-on org-to-anki that might better suit your needs?

**Comment by c-okelly** [comment]
The symbols `[` and `]` might cause problem but they should be fine

**Comment by StohanzlMart** [comment]
Thank you and see you there :)
