### ISSUE TITLE
Error "list index out of range"

### ISSUE THREAD

**Issue by heaneySam** [c-okelly/anki-remote-decks#46]
Hi,

We are getting the following error on [this ](https://docs.google.com/document/d/e/2PACX-1vTDa8ox8uMfU8LodoSP_1gqJAhUWE5BNZEEyWpVFsZGMESrZHqfvTHnMQ8xWq-WFrSZfdoAd8kJYl0r/pub)file.

![image](https://user-images.githubusercontent.com/19505949/73212189-9bc2b880-4145-11ea-8d6d-cdc096fbabe6.png)

I have removed a few things from it (someone put a # randomly in an answer and some of the bullet points weren't quite right) but it seems to still have the error.

Any ideas?

I need to say that I really really appreciate what you're doing. It is massively improving our workflow.

**Comment by c-okelly** [comment]
I will have a look this evening! (5/6 hours and get back to you)! 

I don't see anything obviously wrong in the document

**Comment by c-okelly** [comment]
Closed by v1.5.1 . Released

Strangely enough this was an existing issues in org_to_anki and only happened to come to light today after I made loads of changes.

**Comment by heaneySam** [comment]
Ah, sorry to hear that. But well done for sorting all out. I really appreciate everything you are doing.
