### ISSUE TITLE
Lagging in Sync time

### ISSUE THREAD

**Issue by anki-235** [c-okelly/anki-remote-decks#47]
This is an incredible add-on and I thank you for creating it.
I've noticed that there is considerable lag between when I edit something in the google doc and when it appears in Anki after I click "Sync remote decks". Probably a good 5-10 minutes.

In your GIF showing this update process it look immediate so I was wondering if there was an issue on my end there or if the delay is normal.

Thanks!

**Comment by c-okelly** [comment]
Hey,

Hey, just wondering have you updated recently? I made a lot of efficiency changes recently.

For some of the larger decks I have seen people have nearly 1Gb of imaged and it can take a while to download

Otherwise send me on a link to your deck and I'll have a look. okellyconor@gmail.com if it's a personal deck

**Comment by c-okelly** [comment]
Actually sorry I misread your comment.

If you update something in your Google Doc it'll talk at least 5 minutes to update in the published version.

Unfortunately this is a restriction on Google's side

**Comment by anki-235** [comment]
Thank you for your response! So in the GIF you have showing how to update cards, it seems pretty immediate. I'm guessing that there was actually a 5 min wait between you updating and it appearing in the Anki deck then right?

The other idea I had was re: cloze cards. You know in Anki you can use the command-shift-C to automatically cloze whatever you highlight? In google docs it's not as efficient and you need to manually type out the {{c1:: }}  part. Have you thought of a way to speed this up (and not have the notes look unreadable with all the {{c1:: }} {c2:: }}?)

One idea I had was maybe using highlighting to signify different cloze?

![Screen Shot 2020-01-29 at 11 25 15 PM](https://user-images.githubusercontent.com/60443844/73419837-9ce31980-42ee-11ea-8898-47e8fc05a978.png)

![Screen Shot 2020-01-29 at 11 27 54 PM](https://user-images.githubusercontent.com/60443844/73419953-fb0ffc80-42ee-11ea-836e-fd5a7ecbcf47.png)

**Comment by c-okelly** [comment]
The first time you open a doc and make changes the updates might be instant but after that there is normally some lag between them. It's can also be related to caching.

I open to the idea of a different syntax format for close but I don't think color highlighting will be the way to go tbh.

It's seems more likely then not to cause issues. Not sure what would be best tbj
