### ISSUE TITLE
Cards not coming through to anki consistently

### ISSUE THREAD

**Issue by heaneySam** [c-okelly/anki-remote-decks#48]
Hi there, I am struggling to get cards to come through from the following deck. I have no idea what I'm doing wrong - it seems to be something with copy and pasting into the new deck?

https://docs.google.com/document/d/e/2PACX-1vR5J49cpgsPF-wE3YpGzEnNOnWad4iTQzfvYvsxgrtIE4Nn2vY5CxBYbOAxio3FpHWI0cshruJhugaj/pub

Here is the published deck, only a couple of cards but none of them coming through, any help at all would be super helpful.

**Comment by c-okelly** [comment]
Hey,

So the cards are not appearing and you are not getting an error message?

Is it possible they are duplicates?

**Comment by heaneySam** [comment]
Hey,
Yeah no error messages and zero cards appearing in the deck. There are only 4 cards in the deck, so I can't think why they wouldn't go through. I can't think what I'm doing wrong, but this is happening on a couple of our other decks too.
Cheers,
Sam

**Comment by heaneySam** [comment]
I suppose the main reason I'm raising this is that we have decks which are coming through perfectly for some user, but are showing zero cards for other users. If I knew why I would be able to mitigate it. But it is rather hard to replicate the issue.

**Comment by c-okelly** [comment]
Sorry meant to get back to you sooner.

Could you try the following:

Take a screen shot of exactly which cards came through and which did not?

Create a test anki profile and re sync the decks.see of this works. My guess is you have cards with the same question somewhere else in your collection.

A

**Comment by c-okelly** [comment]
I think this issue raise a large point of having a clearer sync proves anyway. Maybe an optional display GUI or something

**Comment by c-okelly** [comment]
Could not replicate. 

Let me know if you are able to narrow it down or can provide any more context!
