### ISSUE TITLE
How to add tags

### ISSUE THREAD

**Issue by baimi1** [c-okelly/anki-remote-decks#49]
Hi how do I add tags to the cards?

**Comment by c-okelly** [comment]
I have yet to update the docs but it's done as follows:

```org
* Question
# tags=1,2,3
** Answer
```

**Comment by baimi1** [comment]
Is there any way to tag a whole section of cards?

**Comment by c-okelly** [comment]
Sorry forgot to reply. You could add tags to a whole deck but as of now not to a section within the Google doc
