### ISSUE TITLE
If order of Qs (bullets in docs) is changed or altered sync is messed up

### ISSUE THREAD

**Issue by fneurohr22** [c-okelly/anki-remote-decks#51]
hello again!

i just noticed this quite recent bug.

if i have lets say 8 Qs in bullet form in the google docs, that means i have 8 Anki flashcards. If i alter the order, for example before the 7th bullet i add another NEW Qs then when i sync it says i have 9 new cards, then after a while i hit sync again and now it says i have less new cards.

I think this bug happens when the order is altered, first time it happens. before i used to alter the order, copy paste here and there and everything would be normal, when syncing total cards would stay the same.

now it seems it Adds the cards normally, but if i then hit sync again it removes some of the new cards. Its a loop.

any idea? if u need me to record a video showing this please let me know, its a really annoying bug.

the big issue is that if i add a tag to a new card from a recent sync, if i hit sync again(due to me altering the order) it will be removed then re-added but without the tag.

**Comment by c-okelly** [comment]
Hum.

That does sound confusing. I will try and test it later and see if I can reproduce.

If you could make a video it would be really helpful!

**Comment by c-okelly** [comment]
I have been having a look at it but was not able to replicate it from the description anyway.

The way it is currently setup anyway i think if you add a tag if would not update the card with a new tag. Are you adding the tag inline or on the line below?

**Comment by c-okelly** [comment]
Could not replicate so will close for the time being
