### ISSUE TITLE
Only Anki certain pages of a document?

### ISSUE THREAD

**Issue by anki-235** [c-okelly/anki-remote-decks#53]
Hello again! I have been using your add-on daily and am a big fan.

I have been trying a new note taking methods with notes on one page, and Anki questions on the first page. but all in one document. My notes also have bullets in them, so I was wondering if its possible to have something that I can put in the Google Doc to ignore the next page when I sync the deck (i.e. only create Anki cards out of page 1 and not page 2).

Thanks!

**Comment by c-okelly** [comment]
Hey sorry,

I mean to reply and then in total slipped my mind.

The pages are not actually really displayed at all when you publish the document so there is no way to tell where one end / begins.

As an alternative what about being able to mark sections as non-note sections? Something like what I have below?

- Question
  - Answer

#commentSection=on
some general notes about the topics
bla bla
#commentSection=off

- More questions
  - Answers

**Comment by c-okelly** [comment]
Closed and will be completed by #59

**Comment by c-okelly** [comment]
released in V1.7.0
