### ISSUE TITLE
[Feature Request] Multiline Comments

### ISSUE THREAD

**Issue by denzilholles** [c-okelly/anki-remote-decks#59]
Hi, 
I know that you can make single line comments using `# ***` but having a system to make multiline comments, such as: 

`# comment start `
`comment  continues` 
`***`
`***`
`# comment ends`

Would be great! This is to enable long descriptive notes into these Google Docs that do not belong within the Anki Card.

**Comment by c-okelly** [comment]
I think this was related to what I was being discussed in #53. I do like your idea more though

**Comment by c-okelly** [comment]
released in V1.7.0
