### ISSUE TITLE
Line incorrectly processed error - Improve error handling and user feedback

### ISSUE THREAD

**Issue by agdworth** [c-okelly/anki-remote-decks#61]
Hi there,

I'm having difficulty troubleshooting a 'Line incorrectly processed' error that happens when I try to sync my Google Docs file with Anki.

This is the file:
https://docs.google.com/document/d/e/2PACX-1vSNNIjnbC-qtU62REOMbB8fh5vpio4lil2bVXj1dxCJAb70VZh4fkX4QMisHCr-KHjg_5HUerT2HXTF/pub

Is there a way to identify which line is causing the processing error?

Thanks!

Andrew

**Comment by c-okelly** [comment]
Hey,

I will have a look at it this afternoon and try and make a fix and try and improve the error handling as well

**Comment by agdworth** [comment]
Thanks - much appreciated.

**Comment by c-okelly** [comment]
I see the problem if you want a quick fix. 

In the following section there is some wired indentation going on. It goes from `level 1` to `level 3` and then back to `level 2`. 

It should not really break like this though.

```
- What are the Risk factors and signs and symptoms for ectopic pregnancy?:
    - tubal pathology
    - Intrauterine devices
    - Infertility
    - younger or older maternal age
    - smoking
  - Signs and symptoms:
    - GI upset
```

**Comment by c-okelly** [comment]
This fix won't be out till tomorrow at least but if you fix the the indentation on that it should work

**Comment by agdworth** [comment]
Thank you I'll try it out now.

Andrew

**Comment by agdworth** [comment]
Thanks - working perfectly now.

Really appreciate your help.

Andrew

**Comment by c-okelly** [comment]
Update finally
