### ISSUE TITLE
decks don't seem to be syncing properly - Anki 2.1.29

### ISSUE THREAD

**Issue by WintersEnd** [c-okelly/anki-remote-decks#70]
I seem to be having issues syncing the remote deck.

Deleting the deck/adding a new deck works fine.

My issue is syncing a deck that has already been added.

This is what I seem to be experiencing:

- Editing ONLY the answer field (on the google doc) and then pressing on 'sync' (after verifying changes on the published google doc) does not seem to update the card.
- Editing the question field (on the google doc) and then syncing results in a NEW card being made on anki (I believe this is intentional behaviour) however, the old card (with the old question) is still there - and it does not delete it on anki (despite that quetsion not existing anymore on the google doc).
- Deleting a question completely (on the google doc) does not result in it being deleted in anki.
- Adding a new question adds a new card in anki (as intended).
- Deleting a card/changing a card (within anki) and then syncing will re-add the missing card/questions from the google doc.

**Comment by WintersEnd** [comment]
this was using the latest version of anki - i downgraded back down to 2.1.22 and dont have these issues anymOre

**Comment by c-okelly** [comment]
Hey,

Thanks for the expanded error report.

I'm just starting to have a look into this now. There have been a few breaks in the last few months due to the new pace at which Anki is developing and the lack of an SDK

**Comment by c-okelly** [comment]
Can you confirm what version of Anki you saw this error on?

**Comment by WintersEnd** [comment]
2.1.29

I also had the "Advanced Browser" plugin installed - not sure if that would matter. https://ankiweb.net/shared/info/874215009

**Comment by c-okelly** [comment]
I think it is probably the new version. 2.1.26 seems to be the latest stable.

I will make sure it doesn't break anyway

**Comment by Pvictorh** [comment]
I'm having the same issues. My version of Anki is 2.1.29 too.

**Comment by c-okelly** [comment]
Fixed by #72 

Will close issue once the new code is released to Anki

**Comment by c-okelly** [comment]
released in V1.7.1
