### ISSUE TITLE
Doesn't work in Anki for Linux - Model not found for Spanish language setup

### ISSUE THREAD

**Issue by trevonio** [c-okelly/anki-remote-decks#71]
I followed the tutorial to add the remote deck and it doesn't work. It shows an error when I add the url to my google document.

The google doc only has to test questions like in the tutorial. The Anki version is
    
    Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-08-04 22:17:29
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Remote Decks Anki collaboration using Google Docs ['911568091', 2020-07-23T19:01, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    911568091
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

The text is...

"Hey there! It seems an error has occurred while running.

The error was model was not found: Basic.

If you would like me to fix it please report it here: https://github.com/c-okelly/anki-remote-decks/issues

Please be sure to provide as much information as possible. Specifically the file the caused the error."

**Comment by c-okelly** [comment]
This might be related to #70 and I'm just looking into that. 

There have been a few breaks in the last few months due to the new pace at which Anki is developing and the lack of an SDK

**Comment by c-okelly** [comment]
Are you using Anki in any specific language?

**Comment by trevonio** [comment]
> Are you using Anki in any specific language?

Spanish.

**Comment by trevonio** [comment]
You were right. After changing language to English (US) and adding the remote deck again it works. Thanks!

**Comment by c-okelly** [comment]
ye it should still work even if it is in a foreign language. I will have a look and figure out why it did not in this case

**Comment by trevonio** [comment]
I had to stop using remote decks as at the moment is not working even switching the language to english. Can't sync correctly or add any decks. I'll try to check regularly as I think would be a great add to the workflow I was trying to implement for my study.

**Comment by c-okelly** [comment]
Sorry to hear that.

There was a recent fix released for the add-on that should fix the sync issues.

I'm not sure why you can't seem to add a deck for the Spanish setup. I will update once I get to the bottom of the issues

**Comment by trevonio** [comment]
Yes, it seems to work now. I will test it for a few days and write again. Thanks for the quick answer!

**Comment by c-okelly** [comment]
This should be fixed by 680e962

Please update and let me know if you are still having issues.

I saw another potential issues but looking into it

**Comment by trevonio** [comment]
It works now. Thanks.
