### ISSUE TITLE
Minor error in the ReadMe (Not exactly an issue )

### ISSUE THREAD

**Issue by dummifiedme** [c-okelly/anki-remote-decks#75]
![image](https://user-images.githubusercontent.com/68785729/91854697-bc299700-ec81-11ea-8453-d59117d2a515.png)
Please see to the Stop Multi comment: MultilineCommentEnd line. I think there's a minor error.

Good Work Guys! :)

**Comment by c-okelly** [comment]
Thanks for the contribution!

I had to read it more then once to spot it hah. Appreciate it though always best not to confuse people!
