### ISSUE TITLE
Empty decks

### ISSUE THREAD

**Issue by AADavin** [c-okelly/anki-remote-decks#80]
I have used this tool just a couple of times, and I think it is great. However, today I clicked on the syncing button and suddenly of my decks got empty. 

Then, I tried to create a new deck:

https://docs.google.com/document/d/e/2PACX-1vTlqyIX4AnfaTvUHsSK_jfnNJdhvADMwHV7AiddFVKjJUdRrfn5ZGX5EBq8P6eVBoK_R4zJRXa8v4Lm/pub

I can import it but Anki says it has 0 cards. Any help? I am afraid it might be something super obvious I am not doing well. Sorry for not being more explicit with a log file or something but I don't know what I could attach. I am using Version 2.1.35

**Comment by c-okelly** [comment]
Hey I will have a look into it!

**Comment by c-okelly** [comment]
I it look like something might have changed with the way google is setup which is very annoying

**Comment by c-okelly** [comment]
Fix pushed in 1.8.2

If you lost a number of decks you probably need to revert your system to a previous version
