### ISSUE TITLE
Impossible to add a deck after removing

### ISSUE THREAD

**Issue by trevonio** [c-okelly/anki-remote-decks#83]
Hi,

If I remove a deck and try to add it again it gives an error message saying that the deck already exists.

**Comment by scaturigo** [comment]
Do you delete the deck like a classic deck or by do firstly delete deck by tools -> manage remote deck -> remove deck ?

**Comment by trevonio** [comment]
I was deleting it just as a classic deck. I didn't know it was a two steps process. Thanks!
