### ISSUE TITLE
Reduce Automatic Update rate in Google Docs?

### ISSUE THREAD

**Issue by pagkly** [c-okelly/anki-remote-decks#87]
Hi. Thank you for the great add-on.
I got one question though is there a way to reduce Google Docs publish to web refresh rate?

If you check the Google Docs published example, you will see on the top right hand corner
"Automatically updated every 5 minutes".
https://docs.google.com/document/d/e/2PACX-1vQawILe70vt1oZCLn9SdyF9Wo0i7-gQ2owGeghXHxhjx9e8_WclLotuU8mFLglZ1QQUDnmBnhRTabte/pub

Is there a way to reduce it to say 1 minute or instantly?

I believe that's why my changes were not synced after I press the sync button on Anki desktop since Google Docs have not refreshed the new update.

**Comment by c-okelly** [comment]
Hey,

The rate is set by Google. I would imagine it's down to stop a large amount of cahce invalidation.

I would put money on it probably can't be changed

**Comment by pagkly** [comment]
Understandable. Thanks!
