### ISSUE TITLE
Keyboard shortcut for syncing decks

### ISSUE THREAD

**Issue by jeremiasbaur** [c-okelly/anki-remote-decks#90]
I would like to have a keyboard shortcut for syncing decks, so I don't need to navigate to the menu item each time.

**Comment by jeremiasbaur** [comment]
I created a pull request with my implementation for this feature: #91 #

**Comment by c-okelly** [comment]
Looks good. Will close the ticket once I have a release up

**Comment by c-okelly** [comment]
Released. Thanks for you work @jeremiasbaur
